### ISSUE TITLE
Type error: Unknown type `EngineAPICloudProcessingService`

### ISSUE THREAD

**Issue by BusyCityGuy** [Corecii/GreenTea#2]
I downloaded the rbxm from the Releases page, version 0.4.7. 
Loaded into studio version 642 (new solver beta is off)
Getting this error in script analysis:

> ReplicatedStorage.Dependencies.greentea.InstanceClasses
> Type Error: (258,52) Unknown type 'EngineAPICloudProcessingService'

**Comment by Corecii** [comment]
I'll remove this class.

This is expected occasionally due to Roblox updating the API. If you were using this class in your code, it would break in your code too. I don't filter the classes for only one that would usually be publicly accessible.

Most people just set their editors to not show warnings for packages. Frustratingly, I don't think this option exists for Roblox Studio.

**Comment by Corecii** [comment]
Resolved in https://github.com/Corecii/GreenTea/commit/37c57a598208bb5f3fdf0303b8fe056a88f17c22 and published as part of v0.4.9.
